// <auto-generated />
namespace ImageAndTextToDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class missingcolumns2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(missingcolumns2));
        
        string IMigrationMetadata.Id
        {
            get { return "202210081918353_missing-columns2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
